### ISSUE TITLE
Hello, I encountered a problem during the debugging process. I hope you can answer my question

### ISSUE THREAD

**Issue by cyj-Master** [ma-compbio/Hyper-SAGNN#13]
![image](https://github.com/ma-compbio/Hyper-SAGNN/assets/80498776/c2074264-14e4-41fd-bfb3-7cb34e3ffb2a)

**Comment by ruochiz** [comment]
I think it's probably the same as this issue: https://github.com/ma-compbio/Hyper-SAGNN/issues/7

**Comment by ruochiz** [comment]
just push the updates to the repo

**Comment by cyj-Master** [comment]
Thank you very much for your answer, this solves my problem, I am very sorry that I have another question, where do I keep the representation vector of the node, very sorry
