### ISSUE TITLE
Runtime Error: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead

### ISSUE THREAD

**Issue by bala-srini** [ma-compbio/Hyper-SAGNN#3]
Hi,

Thanks for sharing the code. I am currently seeing a runtime error when I try to run the code. I have included the details below. Can you please take a look into this:

python version: 3.6.10
pytorch version: 1.6.0
tensorflow version: 1.15.2

run command: python main.py --data wordnet -f adj

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/__init__.py:1473: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

1.0 -0.5
model_no_randomwalk
no specific train weight
Node type num [40750    18 40752]
[5. 5. 5. ... 5. 5. 5.]
[5. 5. 5. ... 5. 5. 5.] 5.0 5.0
walk type
Traceback (most recent call last):
  File "main.py", line 604, in <module>
    node_list = np.arange(num_list[-1]).astype('int')
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by ruochiz** [comment]
Thanks for your interest. This problem arises as pytorch 1.6.0 no longer supports division of integer tensors. 

A quick fix would be usign pytorch 1.4.0 or 1.5.0 instead. 
If pytorch 1.6.0 is something you want to stick to, then change `node_list = np.arange(num_list[-1]).astype('int')` to `node_list = np.arange(int(num_list[-1])).astype('int')`
If similar error arises, you can fix them following similar method.
