### ISSUE TITLE
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by zkj201607295** [ma-compbio/Hyper-SAGNN#4]
打扰您了，我在运行程序时在random_walk.py文件中的函数preprocess_transition_probs(sg)产生了报错，报错内容如下：
Traceback (most recent call last):
  File "E:/pythonProject/Hyper-SAGNN/Hyper-SAGNN/Code/main.py", line 608, in <module>
    walk_path = random_walk(args, num, train_data)
  File "E:\pythonProject\Hyper-SAGNN\Hyper-SAGNN\Code\random_walk.py", line 263, in random_walk
    preprocess_transition_probs(G)
  File "E:\pythonProject\Hyper-SAGNN\Hyper-SAGNN\Code\random_walk.py", line 110, in preprocess_transition_probs
    alias_t = p.result()
  File "D:\ZKJ\anaconda3\envs\tensorflow2\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "D:\ZKJ\anaconda3\envs\tensorflow2\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
不知如何修改程序可以消除错误，再次对打扰您表示歉意。

**Comment by ruochiz** [comment]
Thanks for your interest in our work. My guess would be that your memory is not big enough for processing the selected dataset. Could you try the GPS dataset (the smallest one) to see if that works?

**Comment by zkj201607295** [comment]
> Thanks for your interest in our work. My guess would be that your memory is not big enough for processing the selected dataset. Could you try the GPS dataset (the smallest one) to see if that works?

Thank you very much for your help in your busy schedule. It's really a memory problem. In addition, can I ask about the application of this model to single cell Hi-C data set? I can't find the program associated with this.

**Comment by ruochiz** [comment]
We are working on adding extra features to the application of our model on scHi-C. The upgraded code will be released soon. Meanwhile, all the datasets used in the manuscript are cited. You should be able to find the datasets and convert them to the format similar to the format of other datasets stored here easily.  For instance, the Ramani et al. dataset can be found here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE84920
