### ISSUE TITLE
Too many warnings of deprecation

### ISSUE THREAD

**Issue by Abel0828** [ma-compbio/Hyper-SAGNN#9]
The code gives tons of warning of Deprecations "Warning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead." The warnings mess up the layout of output messages.

It is just too painful for a user to scrutinize the code piece by piece for this warning. Please fix it. Appreciated!

Edit:
Solved by backing to Pytorch 1.1.

**Comment by ruochiz** [comment]
It should be fixed now. Sorry for the inconvenience. The warning occurs in more recent pytorch versions, which you might have already noticed.
